name: Verify metadata

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    uses: Manta-Epitech-Academy/workshop-metadata-tools/.github/workflows/verify-metadata-reusable.yml@main
